apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-extensions-prometheus
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - endpoints
  - services
  - nodes
  - nodes/metrics
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  - /metrics/cadvisor
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-extensions-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-extensions-prometheus
subjects:
- kind: ServiceAccount
  name: dynatrace-extensions-collector
  namespace: dynatrace