apiVersion: v1
kind: Namespace
metadata:
  name: burger-shop
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: burger-shop
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=  # guest (base64 encoded)
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: burger-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: "-rabbitmq_prometheus.enabled true"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15692  # Prometheus metrics port
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: burger-shop
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
  - port: 15692
    targetPort: 15692
    name: prometheus-metrics  # Prometheus scraping port
  selector:
    app: rabbitmq
